### ISSUE TITLE
랜딩 페이지 수정

### ISSUE THREAD

**Issue by SeoMoonk** [AlltimeOwl/Backend#167]
## TODO
- [ ] 앱 다운로드 링크 수정
- [ ] "페어릿" -> "페이릿" 오타 수정
- [ ] 고객문의 이메일 변경
- [ ] 노션 페이지 링크 연결

## 기타사항
앱스토어
https://apps.apple.com/kr/app/%ED%8E%98%EC%9D%B4%EB%A6%BF-payrit/id6480038044
