### ISSUE TITLE
약속 도메인 데이터 변경

### ISSUE THREAD

**Issue by SeoMoonk** [AlltimeOwl/Backend#172]
## TODO
- [x] 기간에 "시작일" 추가
- [x] 이름 외에 "전화번호" 쌍 추가
- [x] Background Img storage 처리
