### ISSUE TITLE
차용증 도메인 리팩토링(2)

### ISSUE THREAD

**Issue by SeoMoonk** [AlltimeOwl/Backend#25]
### TODO
- [x] client측 작성 요청시 빌리는 상황인지 빌려주는 상황인지에 대한 request 데이터 필요
  - [x] 차용증 작성시, 채권자 혹은 채무자 쪽 데이터가 로그인한 회원의 데이터와 반드시 일치해야함.
  - [x] 차용증 승인시, 작성자의 반대 역할을 검사했을 때 로그인한 회원의 데이터와 반드시 일치해야함.
  - [x] 엔티티에 작성자의 역할이 무엇이었는지 저장
- [x] 상환 시작일(송금일)은 당일 이후여야 하며, 상환 마감일은 상환 시작일 이후여야 한다.
- [x] 이자율은 음수가 될 수 없으며, 최대 20%를 넘을 수도 없다.
- [x] 차용증 리스트 조회시, 상환 진행율(%) 이 제공되어야 함. (일부 상환액 / 전체 금액 * 100)
- [x] 매일 12시 자정에 만기일이 도래한 차용증의 종료 처리가 이루어져야함.
- [ ] 일부 상환 기능 구현 => #29 이슈로 이동

---
### 기타 사항
- v1 배포 진행 전 사항
  - 본인인증을 진행하지 않아도 작성이 가능해야함.
  - 결제 상태를 건너 뛰고 작성이 완료되어야 함.
- 차용증 엔티티 양측(채권자, 채무자) 우편번호 컬럼 추가할지, 통째로 처리할지 선택
- 일부 상환 내역을 따로 저장할지에 대해 논의 필요함.
- 동일한 데이터로 차용증을 여러 번 작성하려는 시도에 대해 막는 것이 필요할지 선택. (or 작성 쿨타임을 둔다던지.)
