### ISSUE TITLE
차용증 도메인 예외 처리 세분화 및 API 명세 수정

### ISSUE THREAD

**Issue by SeoMoonk** [AlltimeOwl/Backend#50]
## TODO
- [x] 기능 수행 시 발행하는 예외 사항 세분화 처리

- [x] Swagger API 명세 가독성 높이기
  - [x] Schema 설명 작성
  - [x] Example Value 처리
  - [x] Status Code 분류

## 기타사항
- [x] 이자 지급일 request 적용 및 저장
