### ISSUE TITLE
문서 유통 정보 저장

### ISSUE THREAD

**Issue by SeoMoonk** [AlltimeOwl/Backend#98]
## TODO
- [x] 작성자 IP 주소
- [ ] 작성자 본인인증 CI 값
- [x] 승인자 IP 주소
- [ ] 승인자 본인인증 CI 값
- [x] 작성 일시
- [x] 승인 일시
- [x] 문서 고유키
- [x] 문서 저장 URL

## 기타 사항
- [x] 파일을 언제 받아올 것인지
- [x] 파일 이름 규격 정의
- [x] Member 정보 암호화 저장 및 연결 해제
