### ISSUE TITLE
이자 및 원금 리팩토링, 자동 삭제 기능

### ISSUE THREAD

**Issue by SeoMoonk** [AlltimeOwl/Backend#99]
## TODO

이자 및 원금 수정
- [x] 이자와 원금, 남은 금액 정돈하여 별도 저장
- [x] detailResponse에서 원금, 이자, 총액, 남은 금액, 체결일 제공

미승인 / 미결제 차용증의 자동 삭제 기능
- [x] 최종 업데이트 시기(update date) 기준으로 일정 기간 이상 지나면 자동 삭제

상환 완료시 상태 완료(만료) 처리
- [x] expried

차용증 기간 만료 제거
- [x] 상환 기일이 지나도 일부 상환이 가능하도록
- [x] 상환 기일이 지나도 메모 작성이 가능하도록
